map_type: costmap

obstacle_range: 10.0 # 2.0
raytrace_range: 15.0 # 3.0

transform_tolerance: 0.2 # 0.0

footprint: [[0.3,0.25], [0.3,-0.25], [-0.3,-0.25], [-0.3,0.25]]
# robot_radius: 0.7 # 0.0
cost_scaling_factor: 5.0

observation_sources: laser_scan_sensor

laser_scan_sensor: {data_type: LaserScan, topic: /scan_multi, marking: true, clearing: true}
